version: 2
jobs:
  fmt:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
        name: Check terraform formatting
        command: "[ -z \"$(terraform fmt -write=false)\" ] || { terraform fmt -write=false -diff; exit 1; }"
  validate:
    docker:
      - image: docker.io/richardalberto/terraform-google-kubernetes-istio
    steps:
      - checkout
      - run:
          name: Validate terrafrom files
          command: |
            terraform init -input=false
            terraform validate
  lint:
    docker:
      - image: wata727/tflint:0.7.2
    steps:
      - checkout
      - run:
          name: lint
          command: |
            tflint *.tf
workflows:
  version: 2
  lint:
    jobs:
      - fmt
      - validate
      - lint