version: 2
jobs:
  fmt:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Check terraform formatting
          command: '[ -z "$(terraform fmt -write=false)" ] || { terraform fmt -write=false -diff; exit 1; }'

  validate:
    docker:
      - image: richardalberto/terraform-helm
    steps:
      - checkout
      - run:
          name: Validate terrafrom files
          command: |
            terraform init -input=false
            terraform validate

  lint:
    docker:
      - image: wata727/tflint:0.7.2
    steps:
      - checkout
      - run:
          name: lint
          command: |
            tflint *.tf

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat version/version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} .

workflows:
  version: 2
  build-n-release:
    jobs:
      - lint
      - validate
      - fmt
      - approval:
          type: approval
          requires:
            - lint
            - validate
            - fmt
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - approval