version: 2
jobs:
  fmt:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Check terraform formatting
          command: '[ -z "$(terraform fmt -write=false)" ] || { terraform fmt -write=false -diff; exit 1; }'

  validate:
    docker:
      - image: richardalberto/terraform-helm
    steps:
      - checkout
      - run:
          name: Validate terrafrom files
          command: |
            terraform init -input=false
            terraform validate

  lint:
    docker:
      - image: wata727/tflint:0.7.2
    steps:
      - checkout
      - run:
          name: lint
          command: |
            tflint *.tf

  publish-github-release:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            apk add curl
            
            VERSION=$(cat version/version)
            DATA=$(cat <<-EOM
              {
                "tag_name": "$VERSION",
                "target_commitish": "${CIRCLE_SHA1}",
                "name": "${VERSION}",
                "body": "",
                "draft": false,
                "prerelease": false
              }
            EOM
            )
            echo ${DATA}

            curl --data "${DATA}" https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases?access_token=${GITHUB_TOKEN}

workflows:
  version: 2
  build-n-release:
    jobs:
      - lint
      - validate
      - fmt
      - approval:
          type: approval
          requires:
            - lint
            - validate
            - fmt
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - approval